import { PERMISSIONS, Permission } from 'react-native-permissions';
import { isIOS } from '../utils/platform';

export type PermissionType = 
  | 'CAMERA'
  | 'MICROPHONE'
  | 'CONTACTS'
  | 'LOCATION'
  | 'LOCATION_ALWAYS'
  | 'STORAGE'
  | 'PHOTOS'
  | 'NOTIFICATIONS'
  | 'BLUETOOTH'
  | 'CALENDAR'
  | 'REMINDERS'
  | 'MOTION'
  | 'MEDIA_LIBRARY'
  | 'SPEECH_RECOGNITION'
  | 'TRACKING'
  | 'FACE_ID'
  | 'SIRI';

export const PERMISSION_TYPES: Record<string, PermissionType> = {
  CAMERA: 'CAMERA',
  MICROPHONE: 'MICROPHONE',
  CONTACTS: 'CONTACTS',
  LOCATION: 'LOCATION',
  LOCATION_ALWAYS: 'LOCATION_ALWAYS',
  STORAGE: 'STORAGE',
  PHOTOS: 'PHOTOS',
  NOTIFICATIONS: 'NOTIFICATIONS',
  BLUETOOTH: 'BLUETOOTH',
  CALENDAR: 'CALENDAR',
  REMINDERS: 'REMINDERS',
  MOTION: 'MOTION',
  MEDIA_LIBRARY: 'MEDIA_LIBRARY',
  SPEECH_RECOGNITION: 'SPEECH_RECOGNITION',
  TRACKING: 'TRACKING',
  FACE_ID: 'FACE_ID',
  SIRI: 'SIRI',
} as const;


/**
 * Permission Map to normalize iOS and Android permission constants.
 */
export const PERMISSION_MAP: Record<PermissionType, Permission | null> = {
  CAMERA: isIOS ? PERMISSIONS.IOS.CAMERA : PERMISSIONS.ANDROID.CAMERA,
  MICROPHONE: isIOS ? PERMISSIONS.IOS.MICROPHONE : PERMISSIONS.ANDROID.RECORD_AUDIO,
  CONTACTS: isIOS ? PERMISSIONS.IOS.CONTACTS : PERMISSIONS.ANDROID.READ_CONTACTS,
  LOCATION: isIOS ? PERMISSIONS.IOS.LOCATION_WHEN_IN_USE : PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION,
  LOCATION_ALWAYS: isIOS ? PERMISSIONS.IOS.LOCATION_ALWAYS : PERMISSIONS.ANDROID.ACCESS_BACKGROUND_LOCATION,
  STORAGE: isIOS ? PERMISSIONS.IOS.PHOTO_LIBRARY : PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
  PHOTOS: isIOS ? PERMISSIONS.IOS.PHOTO_LIBRARY : PERMISSIONS.ANDROID.READ_MEDIA_IMAGES,
  NOTIFICATIONS: isIOS ? null : PERMISSIONS.ANDROID.POST_NOTIFICATIONS,
  BLUETOOTH: isIOS ? PERMISSIONS.IOS.BLUETOOTH : PERMISSIONS.ANDROID.BLUETOOTH_CONNECT,
  CALENDAR: isIOS ? PERMISSIONS.IOS.CALENDARS : PERMISSIONS.ANDROID.READ_CALENDAR,
  REMINDERS: isIOS ? PERMISSIONS.IOS.REMINDERS : null,
  MOTION: isIOS ? PERMISSIONS.IOS.MOTION : PERMISSIONS.ANDROID.ACTIVITY_RECOGNITION,
  MEDIA_LIBRARY: isIOS ? PERMISSIONS.IOS.MEDIA_LIBRARY : PERMISSIONS.ANDROID.READ_MEDIA_VIDEO,
  SPEECH_RECOGNITION: isIOS ? PERMISSIONS.IOS.SPEECH_RECOGNITION : PERMISSIONS.ANDROID.RECORD_AUDIO,
  TRACKING: isIOS ? PERMISSIONS.IOS.APP_TRACKING_TRANSPARENCY : null,
  FACE_ID: isIOS ? PERMISSIONS.IOS.FACE_ID : null,
  SIRI: isIOS ? PERMISSIONS.IOS.SIRI : null,
};
